# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WebMapGLExporter
                                 A QGIS plugin
 Exports a web map using Web Map GL
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-20
        copyright            : (C) 2018 by Champaign County Regional Planning Commission
        email                : info@ccrpc.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WebMapGLExporter class from file WebMapGLExporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qwebmapgl import WebMapGLExporter
    return WebMapGLExporter(iface)
